In [1]:
from sklearn.neighbors import KNeighborsClassifier
import csv
import random
from sklearn import preprocessing
import numpy as np

In [2]:
input = []
test = []
skip = True
with open('mfcc_full.csv', newline='') as csvfile:
    csvreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in csvreader:
        if(skip):
            skip = False
            continue
        temp = []
        for col in row:
            temp = col.split(',')
        if(random.randint(1,12)%7!=0):
            input.append(temp)
        else:
            test.append(temp)
random.shuffle(input)
random.shuffle(test)
Y = [i[0] for i in input]
X = [(i[1:13]) for i in input]
for x in X:
    for i in range(0,12):
        x[i] = float(x[i])
test_Y = [i[0] for i in test]
test_X = [(i[1:13]) for i in test]
for t_x in test_X:
    for i in range(0,12):
        t_x[i] = float(t_x[i])

In [3]:
X_train = np.array(X)
X_scaled = preprocessing.scale(X_train)

In [4]:
neigh = KNeighborsClassifier(n_neighbors=30)
neigh.fit(X_scaled, Y)

KNeighborsClassifier(n_neighbors=30)

In [5]:
pred = neigh.predict(test_X)
prob = neigh.predict_proba(test_X)
print(pred)
#print(test_Y)
print(prob)
correct = []
for i in range(0,len(pred)):
    correct.append(pred[i]==test_Y[i])
    #print(test_Y[i],pred[i],pred[i]==test_Y[i],)
accuracy = correct.count(True)/len(correct)
uniq = set(test_Y)
baseline = 0
for u in uniq:
    if(test_Y.count(u)>baseline):
        baseline = test_Y.count(u)
baseline /= len(correct)
print("Baseline: ",baseline,"\nAccuracy: ",accuracy)

['"US"' '"US"' '"US"' '"US"' '"US"' '"US"' '"US"' '"US"' '"US"' '"US"'
 '"US"' '"US"' '"ES"' '"US"' '"US"' '"US"' '"US"' '"US"' '"US"' '"US"'
 '"US"' '"US"' '"US"' '"US"']
[[0.4        0.1        0.         0.06666667 0.         0.43333333]
 [0.33333333 0.06666667 0.03333333 0.1        0.03333333 0.43333333]
 [0.26666667 0.06666667 0.06666667 0.06666667 0.         0.53333333]
 [0.         0.1        0.         0.1        0.1        0.7       ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.33333333 0.06666667 0.         0.03333333 0.         0.56666667]
 [0.2        0.33333333 0.         0.03333333 0.         0.43333333]
 [0.23333333 0.03333333 0.13333333 0.16666667 0.06666667 0.36666667]
 [0.3        0.16666667 0.         0.06666667 0.         0.46666667]
 [0.3        0.1        0.         0.03333333 0.         0.56666667]
 [0.36666667 0.13333333 0.         0.03333333 0.         0.46666667]
 [0.33333333 0.13333333 0.         0.06666667 0.         0.46666667]
